### ISSUE TITLE
Blockquote quotes don't show in Firefox

### ISSUE THREAD

**Issue by prydonius** [bitnami/hex#142]
Blockquotes in Firefox don't show the quotation icons:

Chrome:
![screen shot 2018-02-07 at 12 59 58](https://user-images.githubusercontent.com/1544861/35915363-e9dacaec-0c06-11e8-9118-c84863722bb8.png)

Firefox:
![screen shot 2018-02-07 at 13 00 03](https://user-images.githubusercontent.com/1544861/35915368-eeddd5d4-0c06-11e8-976d-5ac183f746bb.png)

**Comment by Angelmmiguel** [comment]
Also, we're going to make this quote style as a subclass. By default, most of the time we don't want the quotes.
