### ISSUE TITLE
Fix the font rendering for headers

### ISSUE THREAD

**Issue by Angelmmiguel** [bitnami/hex#152]
Currently, we're not applying any special rule for the font renderization. For headers, the font is displayed wider than the original font. We can fix it applying this rule for headers:

```
-webkit-font-smoothing: antialiased;
```

This only works for Safari, Chrome and Opera. However, it looks fine on FF too.

We don't want to apply this rule globally because it decreases the readability of the text and buttons.

**Comment by lvalverde** [comment]
It only applies for the custom font Interstate which we are not using in this project.
