### ISSUE TITLE
Article has preference over margin-reset

### ISSUE THREAD

**Issue by lvalverde** [bitnami/hex#186]
`.margin-reset` should have preference so it can modify `.articles` margin values.

![screenshot 2018-04-19 11 15 47](https://user-images.githubusercontent.com/47084/39067315-10c01c70-448d-11e8-82ae-ff8713c64ac2.png)
![screenshot 2018-04-19 11 17 10](https://user-images.githubusercontent.com/47084/39067317-11a6dffc-448d-11e8-8aad-671ed7219cab.png)

**Comment by Angelmmiguel** [comment]
For this component, I think it makes sense to force `.articles` to have `margin-top` equals to 0.

**Comment by Angelmmiguel** [comment]
Closed by #191
