### ISSUE TITLE
Buttons in alerts rendered with underlines

### ISSUE THREAD

**Issue by prydonius** [bitnami/hex#216]
In https://github.com/bitnami/hex/pull/205/files#diff-b96ddcdaffba7108940e61b7a6a58e38L15 the global `text-decoration: none` was removed but a special case was added for buttons. This doesn't work inside alerts, though:

![screen shot 2018-08-27 at 15 51 40](https://user-images.githubusercontent.com/1544861/44691234-b655a700-aa12-11e8-9bcc-7852d62d1d5f.png)
![screen shot 2018-08-27 at 16 01 57](https://user-images.githubusercontent.com/1544861/44691239-b9509780-aa12-11e8-842c-d8f42f187dc5.png)

I'm not sure why `.alert a` is preferred over `.button`.

**Comment by Angelmmiguel** [comment]
Thank you for reporting it @prydonius ! I'm gonna update the rule to ignore the `button` classes
