### ISSUE TITLE
Can't override link decoration for hover, active and focus states

### ISSUE THREAD

**Issue by prydonius** [bitnami/hex#217]
Somewhat related to #216, `!important` is required to override the `text-decoration: underline` for link states (hover, active, focus). This might be an issue with us using CSS instead of SCSS in Kubeapps, which will change in https://github.com/kubeapps/kubeapps/issues/549.

![screen shot 2018-08-27 at 16 06 43](https://user-images.githubusercontent.com/1544861/44691389-54e20800-aa13-11e8-9727-9543e67ef39d.png)
![screen shot 2018-08-27 at 16 08 21](https://user-images.githubusercontent.com/1544861/44691433-73e09a00-aa13-11e8-9fd4-c76f3568ad2b.png)

**Comment by Angelmmiguel** [comment]
@prydonius this is a custom component of Kubeapps. You can use the [`.no-decoration`](https://github.com/bitnami/hex/blob/master/packages/hex-core/src/helpers/_anchors.scss#L52) helper in the anchors to avoid the text decoration

**Comment by prydonius** [comment]
@Angelmmiguel my issue was more that I had to use `!important` instead of simply being able to override it, do you know why that is?

**Comment by Angelmmiguel** [comment]
@prydonius probably that's because of the selector priority. I need to check the specific example.

**Comment by prydonius** [comment]
@Angelmmiguel can we reopen this?
